version: '3.8'

services:
  api:
    container_name: lemonade
    build:
      context: ./backend
      dockerfile: Dockerfile.fastapi  # Set the build context to the app directory where Dockerfile is
    image: lemonade
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/code/app 