"""Added phonenumber unique in Customer

Revision ID: 26cf1da82dd5
Revises: de7711a8f4e3
Create Date: 2024-06-23 10:20:19.032414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26cf1da82dd5'
down_revision: Union[str, None] = 'de7711a8f4e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Customer', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Customer', type_='unique')
    # ### end Alembic commands ###
