"""Change id column to UUID in Tenant table

Revision ID: 685ee5b58e42
Revises: 
Create Date: 2024-06-18 20:58:09.184490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '685ee5b58e42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Tenant_email', table_name='Tenant')
    op.drop_index('ix_Tenant_id', table_name='Tenant')
    op.drop_table('Tenant')
    op.drop_index('ix_User_email', table_name='User')
    op.drop_index('ix_User_id', table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"User_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['Tenant.id'], name='User_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='User_pkey')
    )
    op.create_index('ix_User_id', 'User', ['id'], unique=False)
    op.create_index('ix_User_email', 'User', ['email'], unique=True)
    op.create_table('Tenant',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Tenant_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Tenant_pkey')
    )
    op.create_index('ix_Tenant_id', 'Tenant', ['id'], unique=False)
    op.create_index('ix_Tenant_email', 'Tenant', ['email'], unique=True)
    # ### end Alembic commands ###
