"""Removed relationship

Revision ID: abd8fd2afff1
Revises: b8daa0a2fefb
Create Date: 2024-06-22 11:07:30.924823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd8fd2afff1'
down_revision: Union[str, None] = 'b8daa0a2fefb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
