"""rer

Revision ID: b8daa0a2fefb
Revises: cf803b7eb7a4
Create Date: 2024-06-22 10:50:06.283958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8daa0a2fefb'
down_revision: Union[str, None] = 'cf803b7eb7a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Order', sa.Column('slug', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Order', 'slug')
    # ### end Alembic commands ###
