"""Removed slug

Revision ID: de7711a8f4e3
Revises: b151e8bcd514
Create Date: 2024-06-23 10:18:41.059867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de7711a8f4e3'
down_revision: Union[str, None] = 'b151e8bcd514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Company', 'logo_url')
    op.add_column('Order', sa.Column('order_value', sa.Float(), nullable=False))
    op.drop_column('Order', 'slug')
    op.add_column('Order_Item', sa.Column('order_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'Order_Item', 'Order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Order_Item', type_='foreignkey')
    op.drop_column('Order_Item', 'order_id')
    op.add_column('Order', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Order', 'order_value')
    op.add_column('Company', sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
