name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start SSH Agent and add key
        uses: webfactory/ssh-agent@v0.  .3
        with:
          ssh-private-key: ${{ secrets.  }}

      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.AWS_EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'
            cd ~/Wareflow-backend
            git checkout main
            git pull

            docker-compose down
            docker-compose build
            docker-compose up -d
          EOF
        shell: /bin/bash
