name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust this to your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push API image
        uses: docker/build-push-action@v2
        with:
          context: ./app
          file: ./app/Dockerfile.fastapi  # Correct key for Dockerfile path
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/lemonade:latest

      - name: Build and push Caddy image
        uses: docker/build-push-action@v2
        with:
          context: ./caddy
          file: ./caddy/Dockerfile.caddy  # Correct key for Dockerfile path
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/caddy:latest


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check Network Connectivity
        run: ping -c 5 ${{ secrets.SSH_USERNAME }}@${{ secrets.AWS_EC2_PUBLIC_IP }}      
      - name: Deploy to EC2
        run: |
          ssh -T -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/lemonade:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/caddy:latest
            
            cd ~/Wareflow-backend
            git checkout main
            git pull main
            docker-compose down
            docker-compose up -d
          EOF





